---
title: "Winda Maulidda_1800015081_Tugas_R_DataFrame"
author: "Winda Maulidda"
date: "April 11, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Mengakses data .csv
df <- read.csv("https://raw.githubusercontent.com/jokoeliyanto/Kelas-Dasar-Pejuang-Data-2.0/main/Super-Store-Dataset.csv")
# Menampilkan data
df
```

```{r}
# Menampilkan semua nama kolom
names(df)
# Menampilkan Tipe data tiap kolom
str(df)
```
```{r}
#Tugas Individu no 1
# Segmen dengan profit tertinggi
table(df$segment)
```
```{r}
# Memilih atau Mendefinisikan tiap Segment
df_Consumer=df[df['segment']=='Consumer',]
df_Corporate=df[df['segment']=='Corporate',]
df_Home_Office=df[df['segment']=='Home Office',]
```
```{r}
# Menampilkan Total Penjumlahan Profit tiap Segment
print(sum(df_Consumer$profit))
print(sum(df_Corporate$profit))
print(sum(df_Home_Office$profit))
#Jadi, dalam kasus ini segment dengan profit tertinggi adalah Consumer
```

```{r} 
#Tugas Individu No 2
# Category dengan penjualan terbanyak
table(df$category)
```

```{r}
#Memilih Masing-Masing Category
df_Furniture=df[df['category']=='Furniture',]
df_Office_Supplies=df[df['category']=='Office Supplies',]
df_Technology=df[df['category']=='Technology',]
```

```{r}
# Menampilkan Total Penjualan tiap Category
print(sum(df_Furniture$sales))
print(sum(df_Office_Supplies$sales))
print(sum(df_Technology$sales))
#Jadi, dalam kasus ini Category dengan Penjualan Terbanyak adalah Furniture
```
```{r} 
#Tugas Individu No 3
#Sub Category dengan quantity paling sedikit
table(df$sub_category)
```

```{r}
#Memilih Masing-Masing Sub Category
df_Binders=df[df['sub_category']=='Binders',]
df_Paper=df[df['sub_category']=='Paper',]
df_Furnishings=df[df['sub_category']=='Furnishings',]
df_Phones=df[df['sub_category']=='Phones',]
df_Storage=df[df['sub_category']=='Storage',]
df_Art=df[df['sub_category']=='Art',]
df_Accessories=df[df['sub_category']=='Accessories',]
df_Chairs=df[df['sub_category']=='Chairs',]
df_Appliances=df[df['sub_category']=='Appliances',]
df_Labels=df[df['sub_category']=='Labels',]
df_Tables=df[df['sub_category']=='Tables',]
df_Envelopes=df[df['sub_category']=='Envelopes',]
df_Bookcases=df[df['sub_category']=='Bookcases',]
df_Fasteners=df[df['sub_category']=='Fasteners',]
df_Supplies=df[df['sub_category']=='Supplies',]
df_Machines=df[df['sub_category']=='Machines',]
df_Copiers=df[df['sub_category']=='Copiers',]
```

```{r}
# Menampilkan Total Quantity tiap Sub Category
print(sum(df_Accessories$quantity))
print(sum(df_Appliances$quantity))
print(sum(df_Art$quantity))
print(sum(df_Binders$quantity))
print(sum(df_Bookcases$quantity))
print(sum(df_Chairs$quantity))
print(sum(df_Copiers$quantity))
print(sum(df_Envelopes$quantity))
print(sum(df_Fasteners$quantity))
print(sum(df_Furnishings$quantity))
print(sum(df_Labels$quantity))
print(sum(df_Machines$quantity))
print(sum(df_Paper$quantity))
print(sum(df_Phones$quantity))
print(sum(df_Storage$quantity))
print(sum(df_Supplies$quantity))
print(sum(df_Tables$quantity))
#Jadi, dalam kasus ini sub category dengan quantity paling sedikit adalah Copiers
```

## The End
